from enum import Enum

class ACTION(Enum):
	MOVE_FROM_HOME = 1
	MOVE = 2
	MOVE_ONTO_STAR = 3
	MOVE_ONTO_STAR_AND_KILL = 4
	MOVE_ONTO_GLOBE = 5
	MOVE_ONTO_GLOBE_WHERE_OTHER = 6
	MOVE_ONTO_ANOTHER_DIE = 7
	MOVE_ONTO_ANOTHER_KILL = 8
	MOVE_ONTO_VICTORY_ROAD = 9
	MOVE_ONTO_GOAL = 10
	NONE = 11